name: WorldResetter
main: com.andrewsun.worldresetter.WorldResetter
version: 1.0
depend: [Multiverse-Core]
loadbefore: [Multiverse-Core]
author: "Andrew Sun"
website: "http://www.andrewsun.com"

commands:
   resetworld:
      description: Restore a world to a backup.
      usage: /<command> <world>
      permission: worldresetter.reset
      permission-message: You don't have permission to use this command!